# Generated by Django 5.1 on 2024-08-28 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=0, verbose_name='Количество товара')),
                ('session_key', models.CharField(blank=True, max_length=32, null=True)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления товара')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods1.products', verbose_name='Товар магазина')),
            ],
            options={
                'verbose_name': 'Корзину',
                'verbose_name_plural': 'Корзины товаров',
                'db_table': 'cart',
            },
        ),
    ]
