# Generated by Django 5.1 on 2024-12-26 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ('id',), 'verbose_name': 'Корзину', 'verbose_name_plural': 'Корзины товаров'},
        ),
    ]
