# Generated by Django 5.1 on 2024-08-28 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название товара')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, verbose_name='Url товара')),
            ],
            options={
                'verbose_name': 'категорию товара',
                'verbose_name_plural': 'категории товара',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название товара')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, verbose_name='Url товара')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание товара')),
                ('country', models.TextField(blank=True, null=True, verbose_name='Страна, где проиведен данный товар')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Цена товара(рубль)')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Цена товара со скидкой')),
                ('super_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Супер скидка на товар')),
                ('image', models.ImageField(blank=True, null=True, upload_to='goods1_images', verbose_name='Изображение товара')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество товара(шт.)')),
                ('manufacturer', models.TextField(blank=True, null=True, verbose_name='Производитель товара')),
                ('product_brand', models.TextField(blank=True, null=True, verbose_name='Бренд товара')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата добавления товара')),
                ('rating_product', models.DecimalField(decimal_places=0, default=0.0, max_digits=5, verbose_name='Рейтинг товара от 1 ⭐ до 5 ⭐')),
                ('article', models.DecimalField(decimal_places=0, default=0.0, max_digits=4, verbose_name='Артикул товара')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods1.categories', verbose_name='категория товара')),
            ],
            options={
                'verbose_name': 'Товар ',
                'verbose_name_plural': 'Товары ',
                'db_table': 'product',
                'ordering': ('id',),
            },
        ),
    ]
