# Generated by Django 5.1 on 2024-09-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='country',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='Страна, где проиведен данный товар'),
        ),
        migrations.AlterField(
            model_name='products',
            name='manufacturer',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='Производитель товара'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_brand',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='Бренд товара'),
        ),
        migrations.AlterField(
            model_name='products',
            name='published',
            field=models.DateTimeField(auto_now_add=True, db_index=True, max_length=150, verbose_name='Дата добавления товара'),
        ),
    ]
